---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  selector:
    run: {{.Values.runlabel}}
  type: {{.Values.service.type}}
  ports:
    - name: {{.Values.service.appname}}
      port: {{.Values.service.crdpPort}}
      targetPort: {{.Values.service.crdpTargetPort}}
      nodePort: {{.Values.service.crdpNodePort}}